<?xml version="1.0" encoding="utf-8"?><Database Name="silkspan" Class="QueryLinqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=192.168.10.103;Initial Catalog=silkspan;User ID=dotnet" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="silkspanConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TEST_SYSTEM" Member="TEST_SYSTEMs">
    <Type Name="TEST_SYSTEM">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SYSTEM_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>